// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallApi(arg1) {
  return window['go']['main']['App']['CallApi'](arg1);
}

export function GetPref() {
  return window['go']['main']['App']['GetPref']();
}

export function SetPref(arg1) {
  return window['go']['main']['App']['SetPref'](arg1);
}
