// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CallApi(arg1:main.Req):Promise<main.Resp>;

export function GetPref():Promise<main.Pref>;

export function SetPref(arg1:main.Pref):Promise<main.Pref>;
